PRODUCT_DIR := homie

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_SMP := true

TARGET_USES_64_BIT_BINDER := true

TARGET_NO_BOOTLOADER := false
TARGET_NO_KERNEL := false
TARGET_NO_RADIOIMAGE := true

TARGET_BOARD_PLATFORM := homie
TARGET_BOOTLOADER_BOARD_NAME := homie

# Allow passing `--second` to mkbootimg via 2ndbootloader.
TARGET_BOOTLOADER_IS_2ND := false

USE_OPENGL_RENDERER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
MAX_VIRTUAL_DISPLAY_DIMENSION := 1920
TARGET_APP_LAYER_USE_CONTINUOUS_BUFFER := false
TARGET_USE_DEFAULT_HDR_PROPERTY := true

#MESONHWC CONFIG
TARGET_USES_HWC2 := true
HWC_DISPLAY_NUM := 1
HWC_PRIMARY_FRAMEBUFFER_WIDTH := 1920
HWC_PRIMARY_FRAMEBUFFER_HEIGHT := 1080
HWC_PRIMARY_CONNECTOR_TYPE := "hdmi"

# Camera
USE_CAMERA_STUB := false
BOARD_HAVE_FRONT_CAM := false
BOARD_HAVE_BACK_CAM := false
BOARD_USE_USB_CAMERA := true
IS_CAM_NONBLOCK := true
BOARD_HAVE_FLASHLIGHT := false
BOARD_HAVE_HW_JPEGENC := true

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_USERDATAIMAGE_PARTITION_SIZE := 576716800
BOARD_FLASH_BLOCK_SIZE := 4096

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USES_VENDORIMAGE := true
TARGET_COPY_OUT_VENDOR := vendor

ifneq ($(BOARD_BUILD_SYSTEM_ROOT_IMAGE), true)
BOARD_ROOT_EXTRA_FOLDERS += odm
endif

BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := vfat
BOARD_USES_ODMIMAGE := true
TARGET_COPY_OUT_ODM := odm

BOARD_USES_METADATA_PARTITION := true

BOARD_USES_PRODUCTIMAGE := true
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_PRODUCT := product

BOARD_DTBIMAGE_PARTITION_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 25165824
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1879048192
BOARD_VENDORIMAGE_PARTITION_SIZE := 536870912
BOARD_ODMIMAGE_PARTITION_SIZE := 33554432
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 33554432

TARGET_SUPPORTS_64_BIT_APPS := true

ifneq ($(USE_USB_AS_HOST),true)
BOARD_KERNEL_CMDLINE += "otg_device=1"
endif

ifeq ($(BOARD_BUILD_DISABLED_VBMETAIMAGE), true)
ifeq ($(BOARD_BUILD_SYSTEM_ROOT_IMAGE), true)
BOARD_KERNEL_CMDLINE += "root=/dev/mmcblk0p18"
endif
endif

TARGET_SUPPORT_USB_BURNING_V2 := true

TARGET_RECOVERY_FSTAB := device/fts/$(PRODUCT_DIR)/recovery/recovery.fstab

USE_E2FSPROGS := true

BOARD_KERNEL_BASE := 0x0
BOARD_KERNEL_OFFSET := 0x1080000

BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_ALSA_AUDIO := true

# TODO: enable when working on updates
#TARGET_USE_BLOCK_BASE_UPGRADE := true
#TARGET_OTA_UPDATE_DTB := true

BOARD_VNDK_VERSION := current

# TODO: Enable once these can be set
#DEVICE_MANIFEST_FILE := device/linaro/hikey/manifest.xml
#DEVICE_MATRIX_FILE := device/linaro/hikey/compatibility_matrix.xml
