PRODUCT_DIR := homie

LOCAL_KERNEL_HOME ?= common

ANDROID_BUILD_TYPE := 64

PRODUCT_NAME := homie
PRODUCT_DEVICE := homie
PRODUCT_BRAND := Android
PRODUCT_MODEL := FTS-Homie
PRODUCT_MANUFACTURER := FollowTheStack

TARGET_KERNEL_BUILT_FROM_SOURCE := true
